project:
  type: website

website:
  title: "Pavel Hubáček"
  navbar:
    left:
      - research.qmd
      - students.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true